package com.actuate.birt.wear.options;

public interface UIOptions {
	public String getUIOptions();
	
	// Setters
	public void enableAdvancedSort(boolean enable);
	public void enableAggregation(boolean  enable);
	public void enableCalculatedColumns(boolean enable);
	public void enableChartProperty(boolean enable);
	public void enableChartSubType(boolean enable);
	public void enableCollapseExpand(boolean enable);
	public void enableColumnEdit(boolean enable);
	public void enableColumnResize(boolean enable);
	public void enableContentMargin(boolean enable);
	public void enableDataAnalyzer(boolean enable);
	public void enableDataExtraction(boolean enable);
	public void enableEditReport(boolean enable);
	public void enableExportReport(boolean enable);
	public void enableFilter(boolean enable);
	public void enableFacebookComments(boolean enable);
	public void enableFlashGadgetType(boolean enable);
	public void enableFormat(boolean enable);
	public void enableGroupEdit(boolean enable);
	public void enableHideShowItems(boolean enable);
	public void enableHighlight(boolean enable);
	public void enableHoverHighlight(boolean enable);
	public void enableLaunchViewer(boolean enable);
	public void enableLinkToThisPage(boolean enable);
	public void enableMainMenu(boolean enable);
	public void enableMoveColumn(boolean enable);
	public void enablePageBreak(boolean enable);
	public void enablePageNavigation(boolean enable);
	public void enableParameterPage(boolean enable);
	public void enablePrint(boolean enable);
	public void enableReorderColumns(boolean enable);
	public void enableRowResize(boolean enable);
	public void enableSaveDesign(boolean enable);
	public void enableSaveDocument(boolean enable);
	public void enableShowToolTip(boolean enable);
	public void enableSort(boolean enable);
	public void enableSuppressDuplicate(boolean enable);
	public void enableSwitchView(boolean enable);
	public void enableTextEdit(boolean enable);
	public void enableTOC(boolean enable);
	public void enableToolBar(boolean enable);
	public void enableToolbarContextMenu(boolean enable);
	public void enableToolbarHelp(boolean enable);
	public void enableTopBottomNFilter(boolean enable);
	public void enableUndoRedo(boolean enable);
	public void getFeatureMap(boolean enable);
	
	// Getters
	public boolean getAdvancedSort();
	public boolean getAggregation();
	public boolean getCalculatedColumns();
	public boolean getChartProperty();
	public boolean getChartSubType();
	public boolean getCollapseExpand();
	public boolean getColumnEdit();
	public boolean getColumnResize();
	public boolean getContentMargin();
	public boolean getDataAnalyzer();
	public boolean getDataExtraction();
	public boolean getEditReport();
	public boolean getExportReport();
	public boolean getFilter();
	public boolean getFacebookComments();
	public boolean getFlashGadgetType();
	public boolean getFormat();
	public boolean getGroupEdit();
	public boolean getHideShowItems();
	public boolean getHighlight();
	public boolean getHoverHighlight();
	public boolean getLaunchViewer();
	public boolean getLinkToThisPage();
	public boolean getMainMenu();
	public boolean getMoveColumn();
	public boolean getPageBreak();
	public boolean getPageNavigation();
	public boolean getParameterPage();
	public boolean getPrint();
	public boolean getReorderColumns();
	public boolean getRowResize();
	public boolean getSaveDesign();
	public boolean getSaveDocument();
	public boolean getShowToolTip();
	public boolean getSort();
	public boolean getSuppressDuplicate();
	public boolean getSwitchView();
	public boolean getTextEdit();
	public boolean getTOC();
	public boolean getToolBar();
	public boolean getToolbarContextMenu();
	public boolean getToolbarHelp();
	public boolean getTopBottomNFilter();
	public boolean getUndoRedo();
	public boolean getFeatureMap();
}
